/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InventoryCount } from './inventory-count';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * 
 * @export
 * @class BatchRetrieveInventoryCountsResponse
 */
@ObjectType()
export class BatchRetrieveInventoryCountsResponse {
    /**
     * Any errors that occurred during the request.
     * @type {Array<Error>}
     * @memberof BatchRetrieveInventoryCountsResponse
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    errors?: Array<Error>;
    /**
     * The current calculated inventory counts for the requested objects and locations.
     * @type {Array<InventoryCount>}
     * @memberof BatchRetrieveInventoryCountsResponse
     */
    
    @Field(() => [InventoryCount], { nullable: true })
    counts?: Array<InventoryCount>;
    /**
     * The pagination cursor to be used in a subsequent request. If unset, this is the final response.  See the [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination) guide for more information.
     * @type {string}
     * @memberof BatchRetrieveInventoryCountsResponse
     */
    
    @Field({ nullable: true })
    cursor?: string;
}


