/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogIdMapping } from './catalog-id-mapping';
import { CatalogObject } from './catalog-object';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * 
 * @export
 * @class BatchUpsertCatalogObjectsResponse
 */
@ObjectType()
export class BatchUpsertCatalogObjectsResponse {
    /**
     * Any errors that occurred during the request.
     * @type {Array<Error>}
     * @memberof BatchUpsertCatalogObjectsResponse
     */
    
    errors?: Array<Error>;
    /**
     * The created successfully created CatalogObjects.
     * @type {Array<CatalogObject>}
     * @memberof BatchUpsertCatalogObjectsResponse
     */
    
    @Field(() => [CatalogObject], { nullable: true })
    objects?: Array<CatalogObject>;
    /**
     * The database [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) of this update in RFC 3339 format, e.g., \"2016-09-04T23:59:33.123Z\".
     * @type {string}
     * @memberof BatchUpsertCatalogObjectsResponse
     */
    
    @Field({ nullable: true })
    updated_at?: string;
    /**
     * The mapping between client and server IDs for this upsert.
     * @type {Array<CatalogIdMapping>}
     * @memberof BatchUpsertCatalogObjectsResponse
     */
    
    @Field(() => [CatalogIdMapping], { nullable: true })
    id_mappings?: Array<CatalogIdMapping>;
}


