/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * 
 * @export
 * @class BatchDeleteCatalogObjectsRequest
 */
@ObjectType()
export class BatchDeleteCatalogObjectsRequest {
    /**
     * The IDs of the CatalogObjects to be deleted. When an object is deleted, other objects in the graph that depend on that object will be deleted as well (for example, deleting a CatalogItem will delete its CatalogItemVariation.
     * @type {Array<string>}
     * @memberof BatchDeleteCatalogObjectsRequest
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    object_ids?: Array<string>;
}


