/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Order } from './order';
import { OrderReward } from './order-reward';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * 
 * @export
 * @class CalculateOrderRequest
 */
@ObjectType()
export class CalculateOrderRequest {
    /**
     * 
     * @type {Order}
     * @memberof CalculateOrderRequest
     */
    
    @Field(() => Order, { nullable: false })
    order: Order;
    /**
     * Identifies one or more loyalty reward tiers to apply during order calculation. The discounts defined by the reward tiers are added to the order only to preview the effect of applying the specified reward(s). The reward(s) do not correspond to actual redemptions, that is, no `reward`s are created. Therefore, the reward `id`s are random strings used only to reference the reward tier.
     * @type {Array<OrderReward>}
     * @memberof CalculateOrderRequest
     */
    
    @Field(() => [OrderReward], { nullable: true })
    proposed_rewards?: Array<OrderReward>;
}


