/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Money } from './money';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * The summary of a closed cash drawer shift. This model contains only the money counted to start a cash drawer shift, counted at the end of the shift, and the amount that should be in the drawer at shift end based on summing all cash drawer shift events.
 * @export
 * @class CashDrawerShiftSummary
 */
@ObjectType()
export class CashDrawerShiftSummary {
    /**
     * The shift unique ID.
     * @type {string}
     * @memberof CashDrawerShiftSummary
     */
    @Field() 
    id?: string;
    /**
     * The shift current state. See [CashDrawerShiftState](#type-cashdrawershiftstate) for possible values
     * @type {string}
     * @memberof CashDrawerShiftSummary
     */
    @Field() 
    state?: string;
    /**
     * The shift start time in ISO 8601 format.
     * @type {string}
     * @memberof CashDrawerShiftSummary
     */
    @Field() 
    opened_at?: string;
    /**
     * The shift end time in ISO 8601 format.
     * @type {string}
     * @memberof CashDrawerShiftSummary
     */
    @Field() 
    ended_at?: string;
    /**
     * The shift close time in ISO 8601 format.
     * @type {string}
     * @memberof CashDrawerShiftSummary
     */
    @Field() 
    closed_at?: string;
    /**
     * An employee free-text description of a cash drawer shift.
     * @type {string}
     * @memberof CashDrawerShiftSummary
     */
    @Field() 
    description?: string;
    /**
     * 
     * @type {Money}
     * @memberof CashDrawerShiftSummary
     */
    @Field(() => Money) 
    opened_cash_money?: Money;
    /**
     * 
     * @type {Money}
     * @memberof CashDrawerShiftSummary
     */
    @Field(() => Money) 
    expected_cash_money?: Money;
    /**
     * 
     * @type {Money}
     * @memberof CashDrawerShiftSummary
     */
    @Field(() => Money) 
    closed_cash_money?: Money;
}


