/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';

/**
 * 
 * @export
 * @class CatalogInfoResponseLimits
 */
@ObjectType()
export class CatalogInfoResponseLimits {
    /**
     * The maximum number of objects that may appear within a single batch in a `/v2/catalog/batch-upsert` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    batch_upsert_max_objects_per_batch?: number;
    /**
     * The maximum number of objects that may appear across all batches in a `/v2/catalog/batch-upsert` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    batch_upsert_max_total_objects?: number;
    /**
     * The maximum number of object IDs that may appear in a `/v2/catalog/batch-retrieve` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    batch_retrieve_max_object_ids?: number;
    /**
     * The maximum number of results that may be returned in a page of a `/v2/catalog/search` response.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    search_max_page_limit?: number;
    /**
     * The maximum number of object IDs that may be included in a single `/v2/catalog/batch-delete` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    batch_delete_max_object_ids?: number;
    /**
     * The maximum number of item IDs that may be included in a single `/v2/catalog/update-item-taxes` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    update_item_taxes_max_item_ids?: number;
    /**
     * The maximum number of tax IDs to be enabled that may be included in a single `/v2/catalog/update-item-taxes` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    update_item_taxes_max_taxes_to_enable?: number;
    /**
     * The maximum number of tax IDs to be disabled that may be included in a single `/v2/catalog/update-item-taxes` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    update_item_taxes_max_taxes_to_disable?: number;
    /**
     * The maximum number of item IDs that may be included in a single `/v2/catalog/update-item-modifier-lists` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    update_item_modifier_lists_max_item_ids?: number;
    /**
     * The maximum number of modifier list IDs to be enabled that may be included in a single `/v2/catalog/update-item-modifier-lists` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    update_item_modifier_lists_max_modifier_lists_to_enable?: number;
    /**
     * The maximum number of modifier list IDs to be disabled that may be included in a single `/v2/catalog/update-item-modifier-lists` request.
     * @type {number}
     * @memberof CatalogInfoResponseLimits
     */
    @Field() 
    update_item_modifier_lists_max_modifier_lists_to_disable?: number;
}


