/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogModifierOverride } from './catalog-modifier-override';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Options to control the properties of a `CatalogModifierList` applied to a `CatalogItem` instance.
 * @export
 * @class CatalogItemModifierListInfo
 */
@ObjectType()
export class CatalogItemModifierListInfo {
    /**
     * The ID of the `CatalogModifierList` controlled by this `CatalogModifierListInfo`.
     * @type {string}
     * @memberof CatalogItemModifierListInfo
     */
    @Field() 
    modifier_list_id: string;
    /**
     * A set of `CatalogModifierOverride` objects that override whether a given `CatalogModifier` is enabled by default.
     * @type {Array<CatalogModifierOverride>}
     * @memberof CatalogItemModifierListInfo
     */
    @Field(() => [CatalogModifierOverride]) 
    modifier_overrides?: Array<CatalogModifierOverride>;
    /**
     * If 0 or larger, the smallest number of `CatalogModifier`s that must be selected from this `CatalogModifierList`.
     * @type {number}
     * @memberof CatalogItemModifierListInfo
     */
    @Field() 
    min_selected_modifiers?: number;
    /**
     * If 0 or larger, the largest number of `CatalogModifier`s that can be selected from this `CatalogModifierList`.
     * @type {number}
     * @memberof CatalogItemModifierListInfo
     */
    @Field() 
    max_selected_modifiers?: number;
    /**
     * If `true`, enable this `CatalogModifierList`. The default value is `true`.
     * @type {boolean}
     * @memberof CatalogItemModifierListInfo
     */
    @Field() 
    enabled?: boolean;
}


