/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * A named selection for this `SELECTION`-type custom attribute definition.
 * @export
 * @class CatalogCustomAttributeDefinitionSelectionConfigCustomAttributeSelection
 */
@ObjectType()
export class CatalogCustomAttributeDefinitionSelectionConfigCustomAttributeSelection {
    /**
     * Unique ID set by Square.
     * @type {string}
     * @memberof CatalogCustomAttributeDefinitionSelectionConfigCustomAttributeSelection
     */
    
    @Field({ nullable: true })
    uid?: string;
    /**
     * Selection name, unique within `allowed_selections`.
     * @type {string}
     * @memberof CatalogCustomAttributeDefinitionSelectionConfigCustomAttributeSelection
     */
    
    @Field({ nullable: false })
    name: string;
}


