/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * A mapping between a temporary client-supplied ID and a permanent server-generated ID.  When calling [UpsertCatalogObject](#endpoint-Catalog-UpsertCatalogObject) or [BatchUpsertCatalogObjects](#endpoint-Catalog-BatchUpsertCatalogObjects) to create a [CatalogObject](#type-CatalogObject) instance, you can supply a temporary ID for the to-be-created object, especially when the object is to be referenced elsewhere in the same request body. This temporary ID can be any string unique within the call, but must be prefixed by \"#\".  After the request is sumbitted and the object created, a permanent server-generated ID is assigned to the new object. The permanent ID is unique across the Square catalog.
 * @export
 * @class CatalogIdMapping
 */
@ObjectType()
export class CatalogIdMapping {
    /**
     * The client-supplied temporary `#`-prefixed ID for a new `CatalogObject`.
     * @type {string}
     * @memberof CatalogIdMapping
     */
    
    @Field({ nullable: true })
    client_object_id?: string;
    /**
     * The permanent ID for the CatalogObject created by the server.
     * @type {string}
     * @memberof CatalogIdMapping
     */
    
    @Field({ nullable: true })
    object_id?: string;
}


