/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Defines parameters for a CreateDisputeEvidenceFile request.
 * @export
 * @class CreateDisputeEvidenceFileRequest
 */
@ObjectType()
export class CreateDisputeEvidenceFileRequest {
    /**
     * Unique ID. For more information, see [Idempotency](https://developer.squareup.com/docs/docs/working-with-apis/idempotency).
     * @type {string}
     * @memberof CreateDisputeEvidenceFileRequest
     */
    @Field() 
    idempotency_key: string;
    /**
     * The type of evidence you are uploading. See [DisputeEvidenceType](#type-disputeevidencetype) for possible values
     * @type {string}
     * @memberof CreateDisputeEvidenceFileRequest
     */
    @Field() 
    evidence_type?: string;
    /**
     * The MIME type of the uploaded file. One of image/heic, image/heif, image/jpeg, application/pdf,  image/png, image/tiff.
     * @type {string}
     * @memberof CreateDisputeEvidenceFileRequest
     */
    @Field() 
    content_type?: string;
}


