/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Invoice } from './invoice';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * Describes a `CreateInvoice` request.
 * @export
 * @class CreateInvoiceRequest
 */
@ObjectType()
export class CreateInvoiceRequest {
    /**
     * 
     * @type {Invoice}
     * @memberof CreateInvoiceRequest
     */
    
    @Field(() => Invoice, { nullable: false })
    invoice: Invoice;
    /**
     * A unique string that identifies the `CreateInvoice` request. If you do not  provide `idempotency_key` (or provide an empty string as the value), the endpoint  treats each request as independent.  For more information, see [Idempotency](https://developer.squareup.com/docs/docs/working-with-apis/idempotency).
     * @type {string}
     * @memberof CreateInvoiceRequest
     */
    
    @Field({ nullable: true })
    idempotency_key?: string;
}


