/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LoyaltyReward } from './loyalty-reward';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * A response that includes the loyalty reward created.
 * @export
 * @class CreateLoyaltyRewardResponse
 */
@ObjectType()
export class CreateLoyaltyRewardResponse {
    /**
     * Any errors that occurred during the request.
     * @type {Array<Error>}
     * @memberof CreateLoyaltyRewardResponse
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    errors?: Array<Error>;
    /**
     * 
     * @type {LoyaltyReward}
     * @memberof CreateLoyaltyRewardResponse
     */
    
    @Field(() => LoyaltyReward, { nullable: true })
    reward?: LoyaltyReward;
}


