/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DeviceCode } from './device-code';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * 
 * @export
 * @class CreateDeviceCodeResponse
 */
@ObjectType()
export class CreateDeviceCodeResponse {
    /**
     * Any errors that occurred during the request.
     * @type {Array<Error>}
     * @memberof CreateDeviceCodeResponse
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    errors?: Array<Error>;
    /**
     * 
     * @type {DeviceCode}
     * @memberof CreateDeviceCodeResponse
     */
    
    @Field(() => DeviceCode, { nullable: true })
    device_code?: DeviceCode;
}


