/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Shift } from './shift';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Represents a request to create a `Shift`
 * @export
 * @class CreateShiftRequest
 */
@ObjectType()
export class CreateShiftRequest {
    /**
     * Unique string value to insure the idempotency of the operation.
     * @type {string}
     * @memberof CreateShiftRequest
     */
    @Field() 
    idempotency_key?: string;
    /**
     * 
     * @type {Shift}
     * @memberof CreateShiftRequest
     */
    @Field(() => Shift) 
    shift: Shift;
}


