/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * Defines the fields that are included in the response body of a request to the __CreateMobileAuthorizationCode__ endpoint.
 * @export
 * @class CreateMobileAuthorizationCodeResponse
 */
@ObjectType()
export class CreateMobileAuthorizationCodeResponse {
    /**
     * Generated authorization code that connects a mobile application instance to a Square account.
     * @type {string}
     * @memberof CreateMobileAuthorizationCodeResponse
     */
    
    @Field({ nullable: true })
    authorization_code?: string;
    /**
     * The timestamp when `authorization_code` expires in [RFC 3339](https://tools.ietf.org/html/rfc3339) format, e.g., \"2016-09-04T23:59:33.123Z\".
     * @type {string}
     * @memberof CreateMobileAuthorizationCodeResponse
     */
    
    @Field({ nullable: true })
    expires_at?: string;
    /**
     * 
     * @type {Error}
     * @memberof CreateMobileAuthorizationCodeResponse
     */
    
    @Field({ nullable: true })
    error?: Error;
}


