/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomerGroup } from './customer-group';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Defines the body parameters that can be provided in a request to the [CreateCustomerGroup](#endpoint-createcustomegroup) endpoint.
 * @export
 * @class CreateCustomerGroupRequest
 */
@ObjectType()
export class CreateCustomerGroupRequest {
    /**
     * The idempotency key for the request. See the [Idempotency](https://developer.squareup.com/docs/basics/api101/idempotency) guide for more information.
     * @type {string}
     * @memberof CreateCustomerGroupRequest
     */
    
    @Field({ nullable: true })
    idempotency_key?: string;
    /**
     * 
     * @type {CustomerGroup}
     * @memberof CreateCustomerGroupRequest
     */
    
    @Field(() => CustomerGroup, { nullable: false })
    group: CustomerGroup;
}


