/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Defines the body parameters that can be provided in a request to the __CreateMobileAuthorizationCode__ endpoint.
 * @export
 * @class CreateMobileAuthorizationCodeRequest
 */
@ObjectType()
export class CreateMobileAuthorizationCodeRequest {
    /**
     * The Square location ID the authorization code should be tied to.
     * @type {string}
     * @memberof CreateMobileAuthorizationCodeRequest
     */
    @Field() 
    location_id?: string;
}


