/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LoyaltyAccount } from './loyalty-account';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * A request to create a new loyalty account.
 * @export
 * @class CreateLoyaltyAccountRequest
 */
@ObjectType()
export class CreateLoyaltyAccountRequest {
    /**
     * 
     * @type {LoyaltyAccount}
     * @memberof CreateLoyaltyAccountRequest
     */
    
    @Field(() => LoyaltyAccount, { nullable: false })
    loyalty_account: LoyaltyAccount;
    /**
     * A unique string that identifies this `CreateLoyaltyAccount` request.  Keys can be any valid string, but must be unique for every request.
     * @type {string}
     * @memberof CreateLoyaltyAccountRequest
     */
    
    @Field({ nullable: false })
    idempotency_key: string;
}


