/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Checkout } from './checkout';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * Defines the fields that are included in the response body of a request to the __CreateCheckout__ endpoint.
 * @export
 * @class CreateCheckoutResponse
 */
@ObjectType()
export class CreateCheckoutResponse {
    /**
     * 
     * @type {Checkout}
     * @memberof CreateCheckoutResponse
     */
    
    @Field(() => Checkout, { nullable: true })
    checkout?: Checkout;
    /**
     * Any errors that occurred during the request.
     * @type {Array<Error>}
     * @memberof CreateCheckoutResponse
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    errors?: Array<Error>;
}


