/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Represents a group of customer profiles.   Customer groups can be created, modified, and have their membership defined either via  the Customers API or within Customer Directory in the Square Dashboard or Point of Sale.
 * @export
 * @class CustomerGroup
 */
@ObjectType()
export class CustomerGroup {
    /**
     * Unique Square-generated ID for the customer group.
     * @type {string}
     * @memberof CustomerGroup
     */
    
    @Field({ nullable: true })
    id?: string;
    /**
     * Name of the customer group.
     * @type {string}
     * @memberof CustomerGroup
     */
    
    @Field({ nullable: false })
    name: string;
    /**
     * The timestamp when the customer group was created, in RFC 3339 format.
     * @type {string}
     * @memberof CustomerGroup
     */
    
    @Field({ nullable: true })
    created_at?: string;
    /**
     * The timesamp when the customer group was last updated, in RFC 3339 format.
     * @type {string}
     * @memberof CustomerGroup
     */
    
    @Field({ nullable: true })
    updated_at?: string;
}


