/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Describes a `DeleteInvoice` request.
 * @export
 * @class DeleteInvoiceRequest
 */
@ObjectType()
export class DeleteInvoiceRequest {
    /**
     * The version of the `invoice` to delete. If you do not know the version, you can call `GetInvoice` or  `ListInvoices`.
     * @type {number}
     * @memberof DeleteInvoiceRequest
     */
    @Field() 
    version?: number;
}


