/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * 
 * @export
 * @class Device
 */
@ObjectType()
export class Device {
    /**
     * The device\'s Square-issued ID.
     * @type {string}
     * @memberof Device
     */
    
    @Field({ nullable: true })
    id?: string;
    /**
     * The device\'s merchant-specified name.
     * @type {string}
     * @memberof Device
     */
    
    @Field({ nullable: true })
    name?: string;
}


