/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BankAccount } from './bank-account';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Response object returned by GetBankAccountByV1Id.
 * @export
 * @class GetBankAccountByV1IdResponse
 */
@ObjectType()
export class GetBankAccountByV1IdResponse {
    /**
     * Information on errors encountered during the request.
     * @type {Array<Error>}
     * @memberof GetBankAccountByV1IdResponse
     */
    @Field() 
    errors?: Array<Error>;
    /**
     * 
     * @type {BankAccount}
     * @memberof GetBankAccountByV1IdResponse
     */
    @Field(() => BankAccount) 
    bank_account?: BankAccount;
}


