/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EmployeeWage } from './employee-wage';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * A response to a request to get an `EmployeeWage`. Contains the requested `EmployeeWage` objects. May contain a set of `Error` objects if the request resulted in errors.
 * @export
 * @class GetEmployeeWageResponse
 */
@ObjectType()
export class GetEmployeeWageResponse {
    /**
     * 
     * @type {EmployeeWage}
     * @memberof GetEmployeeWageResponse
     */
    
    @Field(() => EmployeeWage, { nullable: true })
    employee_wage?: EmployeeWage;
    /**
     * Any errors that occurred during the request.
     * @type {Array<Error>}
     * @memberof GetEmployeeWageResponse
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    errors?: Array<Error>;
}


