/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Indicates the state of a tracked item quantity in the lifecycle of goods.
 * @export
 * @enum {string}
 */
export enum InventoryState {
    CUSTOM = 'CUSTOM',
    INSTOCK = 'IN_STOCK',
    SOLD = 'SOLD',
    RETURNEDBYCUSTOMER = 'RETURNED_BY_CUSTOMER',
    RESERVEDFORSALE = 'RESERVED_FOR_SALE',
    SOLDONLINE = 'SOLD_ONLINE',
    ORDEREDFROMVENDOR = 'ORDERED_FROM_VENDOR',
    RECEIVEDFROMVENDOR = 'RECEIVED_FROM_VENDOR',
    INTRANSITTO = 'IN_TRANSIT_TO',
    NONE = 'NONE',
    WASTE = 'WASTE',
    UNLINKEDRETURN = 'UNLINKED_RETURN'
}



