/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * Provides customer data that Square uses to deliver an invoice.
 * @export
 * @class InvoiceRecipient
 */
@ObjectType()
export class InvoiceRecipient {
    /**
     * The ID of the customer. This is the customer profile ID that  you provide when creating a draft invoice.
     * @type {string}
     * @memberof InvoiceRecipient
     */
    
    @Field({ nullable: true })
    customer_id?: string;
    /**
     * The recipient\'s given (that is, first) name.
     * @type {string}
     * @memberof InvoiceRecipient
     */
    
    @Field({ nullable: true })
    given_name?: string;
    /**
     * The recipient\'s family (that is, last) name.
     * @type {string}
     * @memberof InvoiceRecipient
     */
    
    @Field({ nullable: true })
    family_name?: string;
    /**
     * The recipient\'s email address.
     * @type {string}
     * @memberof InvoiceRecipient
     */
    
    @Field({ nullable: true })
    email_address?: string;
    /**
     * 
     * @type {Address}
     * @memberof InvoiceRecipient
     */
    
    @Field(() => Address, { nullable: true })
    address?: Address;
    /**
     * The recipient\'s phone number.
     * @type {string}
     * @memberof InvoiceRecipient
     */
    
    @Field({ nullable: true })
    phone_number?: string;
    /**
     * The name of the recipient\'s company.
     * @type {string}
     * @memberof InvoiceRecipient
     */
    
    @Field({ nullable: true })
    company_name?: string;
}


