/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Merchant } from './merchant';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * The response object returned by the [ListMerchant](#endpoint-listmerchant) endpoint.
 * @export
 * @class ListMerchantsResponse
 */
@ObjectType()
export class ListMerchantsResponse {
    /**
     * Information on errors encountered during the request.
     * @type {Array<Error>}
     * @memberof ListMerchantsResponse
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    errors?: Array<Error>;
    /**
     * The requested `Merchant` entities.
     * @type {Array<Merchant>}
     * @memberof ListMerchantsResponse
     */
    
    @Field(() => [Merchant], { nullable: true })
    merchant?: Array<Merchant>;
    /**
     * If the  response is truncated, the cursor to use in next  request to fetch next set of objects.
     * @type {number}
     * @memberof ListMerchantsResponse
     */
    
    @Field({ nullable: true })
    cursor?: number;
}


