/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Associates a loyalty account with the buyer\'s phone number. For more information, see  [Loyalty Overview](/docs/loyalty/overview).
 * @export
 * @class LoyaltyAccountMapping
 */
@ObjectType()
export class LoyaltyAccountMapping {
    /**
     * The Square-assigned ID of the mapping.
     * @type {string}
     * @memberof LoyaltyAccountMapping
     */
    @Field() 
    id?: string;
    /**
     * The type of mapping. See [LoyaltyAccountMappingType](#type-loyaltyaccountmappingtype) for possible values
     * @type {string}
     * @memberof LoyaltyAccountMapping
     */
    @Field() 
    type: string;
    /**
     * The phone number, in E.164 format. For example, \"+14155551111\".
     * @type {string}
     * @memberof LoyaltyAccountMapping
     */
    @Field() 
    value: string;
    /**
     * The timestamp when the mapping was created, in RFC 3339 format.
     * @type {string}
     * @memberof LoyaltyAccountMapping
     */
    @Field() 
    created_at?: string;
}


