/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Unit of area used to measure a quantity.
 * @export
 * @enum {string}
 */
export enum MeasurementUnitArea {
    IMPERIALACRE = 'IMPERIAL_ACRE',
    IMPERIALSQUAREINCH = 'IMPERIAL_SQUARE_INCH',
    IMPERIALSQUAREFOOT = 'IMPERIAL_SQUARE_FOOT',
    IMPERIALSQUAREYARD = 'IMPERIAL_SQUARE_YARD',
    IMPERIALSQUAREMILE = 'IMPERIAL_SQUARE_MILE',
    METRICSQUARECENTIMETER = 'METRIC_SQUARE_CENTIMETER',
    METRICSQUAREMETER = 'METRIC_SQUARE_METER',
    METRICSQUAREKILOMETER = 'METRIC_SQUARE_KILOMETER'
}



