/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * Contains information on the recipient of a fulfillment.
 * @export
 * @class OrderFulfillmentRecipient
 */
@ObjectType()
export class OrderFulfillmentRecipient {
    /**
     * The Customer ID of the customer associated with the fulfillment.  If `customer_id` is provided, the fulfillment recipient\'s `display_name`, `email_address`, and `phone_number` are automatically populated from the targeted customer profile. If these fields are set in the request, the request values will override the information from the customer profile. If the targeted customer profile does not contain the necessary information and these fields are left unset, the request will result in an error.
     * @type {string}
     * @memberof OrderFulfillmentRecipient
     */
    
    @Field({ nullable: true })
    customer_id?: string;
    /**
     * The display name of the fulfillment recipient.  If provided, overrides the value pulled from the customer profile indicated by `customer_id`.
     * @type {string}
     * @memberof OrderFulfillmentRecipient
     */
    
    @Field({ nullable: true })
    display_name?: string;
    /**
     * The email address of the fulfillment recipient.  If provided, overrides the value pulled from the customer profile indicated by `customer_id`.
     * @type {string}
     * @memberof OrderFulfillmentRecipient
     */
    
    @Field({ nullable: true })
    email_address?: string;
    /**
     * The phone number of the fulfillment recipient.  If provided, overrides the value pulled from the customer profile indicated by `customer_id`.
     * @type {string}
     * @memberof OrderFulfillmentRecipient
     */
    
    @Field({ nullable: true })
    phone_number?: string;
    /**
     * 
     * @type {Address}
     * @memberof OrderFulfillmentRecipient
     */
    
    @Field(() => Address, { nullable: true })
    address?: Address;
}


