/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OrderUpdated } from './order-updated';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * 
 * @export
 * @class OrderUpdatedObject
 */
@ObjectType()
export class OrderUpdatedObject {
    /**
     * 
     * @type {OrderUpdated}
     * @memberof OrderUpdatedObject
     */
    
    @Field(() => OrderUpdated, { nullable: true })
    order_updated?: OrderUpdated;
}


