/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Money } from './money';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * A collection of various money amounts.
 * @export
 * @class OrderMoneyAmounts
 */
@ObjectType()
export class OrderMoneyAmounts {
    /**
     * 
     * @type {Money}
     * @memberof OrderMoneyAmounts
     */
    
    @Field(() => Money, { nullable: true })
    total_money?: Money;
    /**
     * 
     * @type {Money}
     * @memberof OrderMoneyAmounts
     */
    
    @Field(() => Money, { nullable: true })
    tax_money?: Money;
    /**
     * 
     * @type {Money}
     * @memberof OrderMoneyAmounts
     */
    
    @Field(() => Money, { nullable: true })
    discount_money?: Money;
    /**
     * 
     * @type {Money}
     * @memberof OrderMoneyAmounts
     */
    
    @Field(() => Money, { nullable: true })
    tip_money?: Money;
    /**
     * 
     * @type {Money}
     * @memberof OrderMoneyAmounts
     */
    
    @Field(() => Money, { nullable: true })
    service_charge_money?: Money;
}


