/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Money } from './money';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * Refunds a payment.
 * @export
 * @class RefundPaymentRequest
 */
@ObjectType()
export class RefundPaymentRequest {
    /**
     *  A unique string that identifies this RefundPayment request. Key can be any valid string but must be unique for every RefundPayment request.  For more information, see [Idempotency keys](https://developer.squareup.com/docs/working-with-apis/idempotency).
     * @type {string}
     * @memberof RefundPaymentRequest
     */
    
    @Field({ nullable: false })
    idempotency_key: string;
    /**
     * 
     * @type {Money}
     * @memberof RefundPaymentRequest
     */
    
    @Field(() => Money, { nullable: false })
    amount_money: Money;
    /**
     * 
     * @type {Money}
     * @memberof RefundPaymentRequest
     */
    
    @Field(() => Money, { nullable: true })
    app_fee_money?: Money;
    /**
     * Unique ID of the payment being refunded.
     * @type {string}
     * @memberof RefundPaymentRequest
     */
    
    @Field({ nullable: false })
    payment_id: string;
    /**
     * A description of the reason for the refund.
     * @type {string}
     * @memberof RefundPaymentRequest
     */
    
    @Field({ nullable: true })
    reason?: string;
}


