/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Merchant } from './merchant';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * The response object returned by the [RetrieveMerchant](#endpoint-retrieveMerchant) endpoint.
 * @export
 * @class RetrieveMerchantResponse
 */
@ObjectType()
export class RetrieveMerchantResponse {
    /**
     * Information on errors encountered during the request.
     * @type {Array<Error>}
     * @memberof RetrieveMerchantResponse
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    errors?: Array<Error>;
    /**
     * 
     * @type {Merchant}
     * @memberof RetrieveMerchantResponse
     */
    
    @Field(() => Merchant, { nullable: true })
    merchant?: Merchant;
}


