/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Customer } from './customer';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Defines the fields that are included in the response body of a request to the RetrieveCustomer endpoint.  One of `errors` or `customer` is present in a given response (never both).
 * @export
 * @class RetrieveCustomerResponse
 */
@ObjectType()
export class RetrieveCustomerResponse {
    /**
     * Any errors that occurred during the request.
     * @type {Array<Error>}
     * @memberof RetrieveCustomerResponse
     */
    @Field() 
    errors?: Array<Error>;
    /**
     * 
     * @type {Customer}
     * @memberof RetrieveCustomerResponse
     */
    @Field(() => Customer) 
    customer?: Customer;
}


