/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LoyaltyAccountMapping } from './loyalty-account-mapping';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * The search criteria for the loyalty accounts.
 * @export
 * @class SearchLoyaltyAccountsRequestLoyaltyAccountQuery
 */
@ObjectType()
export class SearchLoyaltyAccountsRequestLoyaltyAccountQuery {
    /**
     * The set of mappings to use in the loyalty account search.    This cannot be combined with `customer_ids`.    Max: 30 mappings
     * @type {Array<LoyaltyAccountMapping>}
     * @memberof SearchLoyaltyAccountsRequestLoyaltyAccountQuery
     */
    @Field(() => [LoyaltyAccountMapping]) 
    mappings?: Array<LoyaltyAccountMapping>;
    /**
     * The set of customer IDs to use in the loyalty account search.    This cannot be combined with `mappings`.    Max: 30 customer IDs
     * @type {Array<string>}
     * @memberof SearchLoyaltyAccountsRequestLoyaltyAccountQuery
     */
    @Field() 
    customer_ids?: Array<string>;
}


