/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SearchTeamMembersQuery } from './search-team-members-query';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Represents a search request for a filtered list of `TeamMember` objects.
 * @export
 * @class SearchTeamMembersRequest
 */
@ObjectType()
export class SearchTeamMembersRequest {
    /**
     * 
     * @type {SearchTeamMembersQuery}
     * @memberof SearchTeamMembersRequest
     */
    @Field(() => SearchTeamMembersQuery) 
    query?: SearchTeamMembersQuery;
    /**
     * The maximum number of `TeamMember` objects in a page (25 by default).
     * @type {number}
     * @memberof SearchTeamMembersRequest
     */
    @Field() 
    limit?: number;
    /**
     * The opaque cursor for fetching the next page. Read about [pagination](https://developer.squareup.com/docs/docs/working-with-apis/pagination) with Square APIs for more information.
     * @type {string}
     * @memberof SearchTeamMembersRequest
     */
    @Field() 
    cursor?: string;
}


