/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SearchTeamMembersFilter } from './search-team-members-filter';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Represents the parameters in a search for `TeamMember` objects.
 * @export
 * @class SearchTeamMembersQuery
 */
@ObjectType()
export class SearchTeamMembersQuery {
    /**
     * 
     * @type {SearchTeamMembersFilter}
     * @memberof SearchTeamMembersQuery
     */
    @Field(() => SearchTeamMembersFilter) 
    filter?: SearchTeamMembersFilter;
}


