/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Invoice } from './invoice';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * Describes a `SearchInvoices` response.
 * @export
 * @class SearchInvoicesResponse
 */
@ObjectType()
export class SearchInvoicesResponse {
    /**
     * The list of invoices returned by the search.
     * @type {Array<Invoice>}
     * @memberof SearchInvoicesResponse
     */
    
    @Field(() => [Invoice], { nullable: true })
    invoices?: Array<Invoice>;
    /**
     * When a response is truncated, it includes a cursor that you can use in a  subsequent request to fetch the next set of invoices. If empty, this is the final  response.  For more information, see [Pagination](https://developer.squareup.com/docs/docs/working-with-apis/pagination).
     * @type {string}
     * @memberof SearchInvoicesResponse
     */
    
    @Field({ nullable: true })
    cursor?: string;
    /**
     * Information about errors encountered during the request.
     * @type {Array<Error>}
     * @memberof SearchInvoicesResponse
     */
    
    @Field(() => GraphQLJSON, { nullable: true })
    errors?: Array<Error>;
}


