/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SearchSubscriptionsQuery } from './search-subscriptions-query';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * Defines parameters in a [SearchSubscriptions](#endpoint-subscriptions-searchsubscriptions) endpoint  request.
 * @export
 * @class SearchSubscriptionsRequest
 */
@ObjectType()
export class SearchSubscriptionsRequest {
    /**
     * A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for the original query.  For more information, see [Pagination](https://developer.squareup.com/docs/docs/working-with-apis/pagination).
     * @type {string}
     * @memberof SearchSubscriptionsRequest
     */
    @Field() 
    cursor?: string;
    /**
     * The upper limit on the number of subscriptions to return  in the response.   Default: `200`
     * @type {number}
     * @memberof SearchSubscriptionsRequest
     */
    @Field() 
    limit?: number;
    /**
     * 
     * @type {SearchSubscriptionsQuery}
     * @memberof SearchSubscriptionsRequest
     */
    @Field(() => SearchSubscriptionsQuery) 
    query?: SearchSubscriptionsQuery;
}


