/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Money } from './money';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * The hourly wage rate used to compensate an employee for this shift.
 * @export
 * @class ShiftWage
 */
@ObjectType()
export class ShiftWage {
    /**
     * The name of the job performed during this shift. Square labor-reporting UIs may group shifts together by title.
     * @type {string}
     * @memberof ShiftWage
     */
    @Field() 
    title?: string;
    /**
     * 
     * @type {Money}
     * @memberof ShiftWage
     */
    @Field(() => Money) 
    hourly_rate?: Money;
}


