/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Whether to the tax amount should be additional to or included in the CatalogItem price.
 * @export
 * @enum {string}
 */
export enum TaxInclusionType {
    ADDITIVE = 'ADDITIVE',
    INCLUSIVE = 'INCLUSIVE'
}



