/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumerates the possible statuses the team member can have within a business.
 * @export
 * @enum {string}
 */
export enum TeamMemberStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE'
}



