/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';
import { Refund } from './refund';
import { Tender } from './tender';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * Represents a transaction processed with Square, either with the Connect API or with Square Point of Sale.  The `tenders` field of this object lists all methods of payment used to pay in the transaction.
 * @export
 * @class Transaction
 */
@ObjectType()
export class Transaction {
    /**
     * The transaction\'s unique ID, issued by Square payments servers.
     * @type {string}
     * @memberof Transaction
     */
    
    @Field({ nullable: true })
    id?: string;
    /**
     * The ID of the transaction\'s associated location.
     * @type {string}
     * @memberof Transaction
     */
    
    @Field({ nullable: true })
    location_id?: string;
    /**
     * The timestamp for when the transaction was created, in RFC 3339 format.
     * @type {string}
     * @memberof Transaction
     */
    
    @Field({ nullable: true })
    created_at?: string;
    /**
     * The tenders used to pay in the transaction.
     * @type {Array<Tender>}
     * @memberof Transaction
     */
    
    @Field(() => [Tender], { nullable: true })
    tenders?: Array<Tender>;
    /**
     * Refunds that have been applied to any tender in the transaction.
     * @type {Array<Refund>}
     * @memberof Transaction
     */
    
    @Field(() => [Refund], { nullable: true })
    refunds?: Array<Refund>;
    /**
     * If the transaction was created with the `Charge` endpoint, this value is the same as the value provided for the `reference_id` parameter in the request to that endpoint. Otherwise, it is not set.
     * @type {string}
     * @memberof Transaction
     */
    
    @Field({ nullable: true })
    reference_id?: string;
    /**
     * The Square product that processed the transaction. See [TransactionProduct](#type-transactionproduct) for possible values
     * @type {string}
     * @memberof Transaction
     */
    
    @Field({ nullable: true })
    product?: string;
    /**
     * If the transaction was created in the Square Point of Sale app, this value is the ID generated for the transaction by Square Point of Sale.  This ID has no relationship to the transaction\'s canonical `id`, which is generated by Square\'s backend servers. This value is generated for bookkeeping purposes, in case the transaction cannot immediately be completed (for example, if the transaction is processed in offline mode).  It is not currently possible with the Connect API to perform a transaction lookup by this value.
     * @type {string}
     * @memberof Transaction
     */
    
    @Field({ nullable: true })
    client_id?: string;
    /**
     * 
     * @type {Address}
     * @memberof Transaction
     */
    
    @Field(() => Address, { nullable: true })
    shipping_address?: Address;
    /**
     * The order_id is an identifier for the order associated with this transaction, if any.
     * @type {string}
     * @memberof Transaction
     */
    
    @Field({ nullable: true })
    order_id?: string;
}


