/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Shift } from './shift';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * A request to update a `Shift` object.
 * @export
 * @class UpdateShiftRequest
 */
@ObjectType()
export class UpdateShiftRequest {
    /**
     * 
     * @type {Shift}
     * @memberof UpdateShiftRequest
     */
    
    @Field(() => Shift, { nullable: false })
    shift: Shift;
}


