/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogObject } from './catalog-object';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * 
 * @export
 * @class UpsertCatalogObjectRequest
 */
@ObjectType()
export class UpsertCatalogObjectRequest {
    /**
     * A value you specify that uniquely identifies this request among all your requests. A common way to create a valid idempotency key is to use a Universally unique identifier (UUID).  If you\'re unsure whether a particular request was successful, you can reattempt it with the same idempotency key without worrying about creating duplicate objects.  See [Idempotency](https://developer.squareup.com/docs/basics/api101/idempotency) for more information.
     * @type {string}
     * @memberof UpsertCatalogObjectRequest
     */
    @Field() 
    idempotency_key: string;
    /**
     * 
     * @type {CatalogObject}
     * @memberof UpsertCatalogObjectRequest
     */
    @Field(() => CatalogObject) 
    object: CatalogObject;
}


