/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Page } from './v1-page';

import { Field, ObjectType } from '@nestjs/graphql';

/**
 * 
 * @export
 * @class V1CreatePageRequest
 */
@ObjectType()
export class V1CreatePageRequest {
    /**
     * 
     * @type {V1Page}
     * @memberof V1CreatePageRequest
     */
    
    @Field(() => V1Page, { nullable: true })
    body?: V1Page;
}


