/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum V1ItemColor {
    _9da2a6 = '9da2a6',
    _4ab200 = '4ab200',
    _0b8000 = '0b8000',
    _2952cc = '2952cc',
    A82ee5 = 'a82ee5',
    E5457a = 'e5457a',
    B21212 = 'b21212',
    _593c00 = '593c00',
    E5BF00 = 'e5BF00'
}



