/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Category } from './v1-category';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * 
 * @export
 * @class V1ListCategoriesResponse
 */
@ObjectType()
export class V1ListCategoriesResponse {
    /**
     * 
     * @type {Array<V1Category>}
     * @memberof V1ListCategoriesResponse
     */
    
    @Field(() => [V1Category], { nullable: true })
    items?: Array<V1Category>;
}


