/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1InventoryEntry } from './v1-inventory-entry';

import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * 
 * @export
 * @class V1ListInventoryResponse
 */
@ObjectType()
export class V1ListInventoryResponse {
    /**
     * 
     * @type {Array<V1InventoryEntry>}
     * @memberof V1ListInventoryResponse
     */
    
    @Field(() => [V1InventoryEntry], { nullable: true })
    items?: Array<V1InventoryEntry>;
}


