/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Actions that resulted in a change to a timecard. All timecard events created with the Connect API have an event type that begins with `API`.
 * @export
 * @enum {string}
 */
export enum V1TimecardEventEventType {
    APICREATE = 'API_CREATE',
    APIEDIT = 'API_EDIT',
    APIDELETE = 'API_DELETE',
    REGISTERCLOCKIN = 'REGISTER_CLOCKIN',
    REGISTERCLOCKOUT = 'REGISTER_CLOCKOUT',
    DASHBOARDSUPERVISORCLOSE = 'DASHBOARD_SUPERVISOR_CLOSE',
    DASHBOARDEDIT = 'DASHBOARD_EDIT',
    DASHBOARDDELETE = 'DASHBOARD_DELETE'
}



