/* tslint:disable */
/* eslint-disable */
/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { Field, ObjectType } from '@nestjs/graphql';
import GraphQLJSON from 'graphql-type-json';

/**
 * V1TimecardEvent
 * @export
 * @class V1TimecardEvent
 */
@ObjectType()
export class V1TimecardEvent {
    /**
     * The event\'s unique ID.
     * @type {string}
     * @memberof V1TimecardEvent
     */
    
    @Field({ nullable: true })
    id?: string;
    /**
     * The ID of the timecard to list events for. See [V1TimecardEventEventType](#type-v1timecardeventeventtype) for possible values
     * @type {string}
     * @memberof V1TimecardEvent
     */
    
    @Field({ nullable: true })
    event_type?: string;
    /**
     * The time the employee clocked in, in ISO 8601 format.
     * @type {string}
     * @memberof V1TimecardEvent
     */
    
    @Field({ nullable: true })
    clockin_time?: string;
    /**
     * The time the employee clocked out, in ISO 8601 format.
     * @type {string}
     * @memberof V1TimecardEvent
     */
    
    @Field({ nullable: true })
    clockout_time?: string;
    /**
     * The time when the event was created, in ISO 8601 format.
     * @type {string}
     * @memberof V1TimecardEvent
     */
    
    @Field({ nullable: true })
    created_at?: string;
}


